dist: bionic
language: python
services:
  - redis-server
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script: pytest --color=yes --verbose --showlocals
